{"name": "test_6", "status": "skipped", "statusDetails": {"message": "XFAIL\n\nAssertionError: assert 1000 > 20000", "trace": "@pytest.mark.xfail\n    def test_6():\n        a = 1000\n        b = 20000\n    \n>       assert a > b\nE       assert 1000 > 20000\n\nSeleniumProgram\\test_markers.py:59: AssertionError"}, "start": 1673445632204, "stop": 1673445632204, "uuid": "c5c8891b-6f12-4495-b646-534a3a64174c", "historyId": "9d03cf3521012e9ee6c3e597d9d46c2d", "testCaseId": "40767d43dbbd46bc0fa4df4b2b2e73ca", "fullName": "test_markers#test_6", "labels": [{"name": "tag", "value": "@pytest.mark.xfail"}, {"name": "suite", "value": "test_markers"}, {"name": "host", "value": "HP"}, {"name": "thread", "value": "43844-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_markers"}]}